package org.lgq.iot.sdk.mqtt.constant;


import lombok.Getter;

@Getter
public enum CertEnum {

    CN_NORTH_4_SHARE_INSTANCE("121.36.42.100", CertPath.CN_NORTH_4_SHARE_INSTANCE_CERTPATH),

    CN_NORTH_4_STANDARD_INSTANCE("117.78.5.125", CertPath.CN_NORTH_4_STANDARD_INSTANCE_CERTPATH),
    CN_EAST_3_STANDARD_INSTANCE("124.70.218.131", CertPath.CN_NORTH_4_STANDARD_INSTANCE_CERTPATH),
    CN_SOUTH_1_STANDARD_INSTANCE("116.205.178.237", CertPath.CN_NORTH_4_STANDARD_INSTANCE_CERTPATH),
    CN_SOUTH_4_STANDARD_INSTANCE("123.60.224.23", CertPath.CN_NORTH_4_STANDARD_INSTANCE_CERTPATH),

    AP_SOUTHEASR_1_STANDARD_INSTANCE("182.160.7.139", CertPath.AP_SOUTHEASR_1_STANDARD_INSTANCE__CERTPATH),
    AP_SOUTHEASR_2_STANDARD_INSTANCE("43.255.105.212", CertPath.AP_SOUTHEASR_2_STANDARD_INSTANCE__CERTPATH),
    AP_SOUTHEASR_3_STANDARD_INSTANCE("119.8.186.222", CertPath.AP_SOUTHEASR_3_STANDARD_INSTANCE__CERTPATH),
    ;

    private final String ip;
    private final String certPath;

    CertEnum(String ip, String certPath) {
        this.ip = ip;
        this.certPath = certPath;
    }
}
